export const DELULU_ABI = [
  {
    inputs: [
      { internalType: "address", name: "stablecoinAddress", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyClaimed", type: "error" },
  { inputs: [], name: "AlreadyResolved", type: "error" },
  { inputs: [], name: "DeluluNotFound", type: "error" },
  { inputs: [], name: "EmptyContentHash", type: "error" },
  { inputs: [], name: "InsufficientStake", type: "error" },
  { inputs: [], name: "InvalidDeadlines", type: "error" },
  { inputs: [], name: "InvalidTokenAddress", type: "error" },
  { inputs: [], name: "NoStakeToRefund", type: "error" },
  { inputs: [], name: "NotRefundable", type: "error" },
  { inputs: [], name: "NotResolved", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "QueryTooLarge", type: "error" },
  { inputs: [], name: "ResolutionDeadlineTooFar", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "SlippageTooHigh", type: "error" },
  { inputs: [], name: "StakeLimitExceeded", type: "error" },
  { inputs: [], name: "StakeTooLarge", type: "error" },
  { inputs: [], name: "StakeTooSmall", type: "error" },
  { inputs: [], name: "StakingDeadlineTooFar", type: "error" },
  { inputs: [], name: "StakingIsClosed", type: "error" },
  { inputs: [], name: "StakingNotYetClosed", type: "error" },
  { inputs: [], name: "TransferFailed", type: "error" },
  { inputs: [], name: "UserIsNotWinner", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "contentHash",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "stakingDeadline",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "resolutionDeadline",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "creatorStake",
        type: "uint256",
      },
    ],
    name: "DeluluCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "outcome", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "winningPool",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "losingPool",
        type: "uint256",
      },
    ],
    name: "DeluluResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
    ],
    name: "DelululCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EmergencyRefund",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FeeCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FeesWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "side", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "newTotalPoolStake",
        type: "uint256",
      },
    ],
    name: "StakePlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "deluluId",
        type: "uint256",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "payout",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "feeCharged",
        type: "uint256",
      },
    ],
    name: "WinningsClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EMERGENCY_REFUND_DELAY",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DELULUS_PER_QUERY",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_RESOLUTION_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_STAKE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_STAKE_PER_USER",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_STAKING_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_STAKE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PLATFORM_FEE_BPS",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deluluId", type: "uint256" }],
    name: "cancelDelulu",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deluluId", type: "uint256" }],
    name: "claimWinnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "contentHash", type: "string" },
      { internalType: "uint256", name: "stakingDeadline", type: "uint256" },
      { internalType: "uint256", name: "resolutionDeadline", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "createDelulu",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "delulus",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "string", name: "contentHash", type: "string" },
      { internalType: "uint256", name: "stakingDeadline", type: "uint256" },
      { internalType: "uint256", name: "resolutionDeadline", type: "uint256" },
      { internalType: "uint256", name: "totalBelieverStake", type: "uint256" },
      { internalType: "uint256", name: "totalDoubterStake", type: "uint256" },
      { internalType: "bool", name: "outcome", type: "bool" },
      { internalType: "bool", name: "isResolved", type: "bool" },
      { internalType: "bool", name: "isCancelled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deluluId", type: "uint256" }],
    name: "emergencyRefund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deluluId", type: "uint256" }],
    name: "getDelulu",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "string", name: "contentHash", type: "string" },
          { internalType: "uint256", name: "stakingDeadline", type: "uint256" },
          {
            internalType: "uint256",
            name: "resolutionDeadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalBelieverStake",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalDoubterStake",
            type: "uint256",
          },
          { internalType: "bool", name: "outcome", type: "bool" },
          { internalType: "bool", name: "isResolved", type: "bool" },
          { internalType: "bool", name: "isCancelled", type: "bool" },
        ],
        internalType: "struct DeluluMarket.Delulu",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "deluluId", type: "uint256" }],
    name: "getDeluluState",
    outputs: [
      {
        internalType: "enum DeluluMarket.DeluluState",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "startId", type: "uint256" },
      { internalType: "uint256", name: "count", type: "uint256" },
    ],
    name: "getDelulus",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "string", name: "contentHash", type: "string" },
          { internalType: "uint256", name: "stakingDeadline", type: "uint256" },
          {
            internalType: "uint256",
            name: "resolutionDeadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalBelieverStake",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalDoubterStake",
            type: "uint256",
          },
          { internalType: "bool", name: "outcome", type: "bool" },
          { internalType: "bool", name: "isResolved", type: "bool" },
          { internalType: "bool", name: "isCancelled", type: "bool" },
        ],
        internalType: "struct DeluluMarket.Delulu[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "deluluId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "isBeliever", type: "bool" },
    ],
    name: "getPotentialPayout",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "deluluId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "getUserPosition",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "bool", name: "side", type: "bool" },
          { internalType: "bool", name: "claimed", type: "bool" },
        ],
        internalType: "struct DeluluMarket.UserPosition",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "deluluId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "isClaimable",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextDeluluId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "deluluId", type: "uint256" },
      { internalType: "bool", name: "outcome", type: "bool" },
    ],
    name: "resolveDelulu",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stablecoin",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "deluluId", type: "uint256" },
      { internalType: "bool", name: "side", type: "bool" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "minPayout", type: "uint256" },
    ],
    name: "stakeOnDelulu",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalFeesCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "userStakes",
    outputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "bool", name: "side", type: "bool" },
      { internalType: "bool", name: "claimed", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "userTotalStaked",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
