"use client";

import { env } from "@/lib/env";

export type PushSupportState =
  | { state: "unsupported" }
  | { state: "needs_permission"; permission: NotificationPermission }
  | { state: "ready"; permission: NotificationPermission; subscribed: boolean };

function urlBase64ToUint8Array(base64String: string) {
  // VAPID public keys are commonly base64url, but can be pasted with
  // whitespace/PEM headers. Normalize, then decode without `atob`
  // (browser `atob` is strict and throws on certain non-padded inputs).
  let s = (base64String || "").trim();

  // PEM support: extract the base64 body if headers/footers exist.
  s = s
    .replace(/-----BEGIN [^-]+-----/g, "")
    .replace(/-----END [^-]+-----/g, "")
    .replace(/\s+/g, "");

  // Convert base64url -> base64 alphabet.
  s = s.replace(/-/g, "+").replace(/_/g, "/");

  // Defensive: remove anything outside the base64 alphabet.
  s = s.replace(/[^A-Za-z0-9+/=]/g, "");

  // Base64 decoder (base64url-safe) using bit accumulation.
  // This avoids `atob` strictness and works for padded/unpadded base64.
  const alphabet =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  let bits = 0;
  let bitLen = 0;
  const out: number[] = [];

  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (ch === "=") continue; // padding doesn't contribute bits
    const val = alphabet.indexOf(ch);
    if (val < 0) continue; // skip unexpected chars defensively
    bits = (bits << 6) | val;
    bitLen += 6;
    while (bitLen >= 8) {
      bitLen -= 8;
      out.push((bits >> bitLen) & 0xff);
    }
  }

  const bytes = new Uint8Array(out);

  // VAPID public keys generated by web-push are typically 65 bytes
  // (uncompressed EC point with 0x04 prefix).
  if (bytes.length !== 65) {
    // Throw a descriptive error so the user can fix env.
    throw new Error(
      `Invalid VAPID public key: decoded length ${bytes.length} bytes (expected 65). ` +
        `Check NEXT_PUBLIC_VAPID_PUBLIC_KEY; it may be truncated or copied incorrectly.`
    );
  }

  return bytes;
}

export async function getPushSupportState(): Promise<PushSupportState> {
  if (typeof window === "undefined") return { state: "unsupported" };
  if (!("serviceWorker" in navigator) || !("PushManager" in window)) {
    return { state: "unsupported" };
  }
  if (!("Notification" in window)) return { state: "unsupported" };

  const permission = Notification.permission;
  const reg = await navigator.serviceWorker.getRegistration("/");
  const sub = reg ? await reg.pushManager.getSubscription() : null;

  if (permission !== "granted") {
    return { state: "needs_permission", permission };
  }
  return { state: "ready", permission, subscribed: Boolean(sub) };
}

export async function ensureServiceWorker(): Promise<ServiceWorkerRegistration> {
  const reg =
    (await navigator.serviceWorker.getRegistration("/")) ??
    (await navigator.serviceWorker.register("/sw.js", { scope: "/" }));
  return reg;
}

export async function subscribeToWebPush(address: string): Promise<void> {
  if (!env.NEXT_PUBLIC_VAPID_PUBLIC_KEY) {
    throw new Error("Push is not configured (missing VAPID public key).");
  }
  const reg = await ensureServiceWorker();

  const permission = await Notification.requestPermission();
  if (permission !== "granted") {
    throw new Error("Notifications permission not granted.");
  }

  const existing = await reg.pushManager.getSubscription();
  const subscription =
    existing ??
    (await reg.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(env.NEXT_PUBLIC_VAPID_PUBLIC_KEY),
    }));

  const json = subscription.toJSON();

  const res = await fetch("/api/push/subscribe", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      address,
      subscription: {
        endpoint: subscription.endpoint,
        keys: json.keys,
      },
    }),
  });
  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data?.error ?? "Failed to save push subscription.");
  }
}

export async function unsubscribeWebPush(address: string): Promise<void> {
  const reg = await navigator.serviceWorker.getRegistration("/");
  const sub = reg ? await reg.pushManager.getSubscription() : null;
  if (sub) {
    await sub.unsubscribe().catch(() => {});
  }
  await fetch("/api/push/unsubscribe", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ address, endpoint: sub?.endpoint ?? null }),
  }).catch(() => {});
}

